homework_1
fintech-kotlin/nikolaev-cashback-service pull request #1
Opened 2020-02-24 18:06 UTC by likusta

# Выполнено задание № 1

## В процесс было сделано:
 - реализован метод, который маскирует цифры в номере карты
 - реализован метод, который генерирует  персонифицированное сообщение

## PR чеклист:
 - [X] В Project выставлен `Tinkoff "Java to Kotlin"`
 - [X] Добавлен label с номером домашнего задания

2020-02-25 12:19 UTC, KazakovIgor requested changes

2020-02-25 12:19 UTC, KazakovIgor commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +        }
Код, который ничего не делает можно и не писать =)

2020-02-25 12:19 UTC, KazakovIgor commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +        if (cardNumber.equals("")) {
Идея подсказывает заменить equals на == (cardNumber == "" ) Оператор == эквивалентен equals()
Но в данном случае лучше написать cardNumber.isEmpty()

2020-02-25 12:19 UTC, KazakovIgor commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +            return cardNumber.replaceRange(
Idea подсказывает, что return можно вынести перед if. В этом случае тип возвращаемого значения можно явно не указывать

2020-02-25 12:19 UTC, KazakovIgor commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/NotificationMessageGeneratorImpl.kt
> +        return "Уважаемый, " + notificationMessageInfo.name + "!\n" +
1. Можно использовать многострочный текст и функцию trimIndent()
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/trim-indent.html
2. Лучше использовать String Interpolation
https://kotlinlang.org/docs/reference/idioms.html#string-interpolation

2020-02-25 12:19 UTC, KazakovIgor commented on src/main/kotlin/ru/tinkoff/fintech/model/NotificationMessageInfo.kt
> +    var name: String,
А зачем?

2020-02-26 09:09 UTC, likusta commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +        }
Обрадовался, что всё заработал и забыл удалить) Спасибо)

2020-02-26 09:09 UTC, likusta commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +        if (cardNumber.equals("")) {
Понял, спасибо!

2020-02-26 09:11 UTC, likusta commented on src/main/kotlin/ru/tinkoff/fintech/model/NotificationMessageInfo.kt
> +    var name: String,
Когда начал решать задачу подумал, является ли имя изменяемым полем, было интересно протестировать, так это и осталось. Вернул обратно. Извините.

2020-02-26 17:48 UTC, KazakovIgor approved these changes

2020-02-26 17:48 UTC, KazakovIgor commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/NotificationMessageGeneratorImpl.kt
> +        return "Уважаемый, ${notificationMessageInfo.name}!\n" +
1. Довольно тяжело читать такой код. Если хочется указывать каждый параметр в новой строке, в данном случае, лучше использовать именованные параметры.
2. Можно использовать многострочный текст и функцию trimIndent()
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/trim-indent.html

2020-05-06 23:44 UTC, closed without merging